/*
 * MapStores.cpp
 *
 *  Created on: 21 Mar 2020
 *      Author: Debashis
 */

#include "MapStores.h"

namespace agentStore
{
	std::unordered_map<uint32_t, TcpPacket*> tcpAStore[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool tcpABusy[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t tcpACnt[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, UdpPacket*> udpAStore[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool udpABusy[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t udpACnt[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, AAAPacket*> aaaAStore[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool aaaABusy[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t aaaACnt[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, DnsPacket*> dnsAStore[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool dnsABusy[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t dnsACnt[MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

}

namespace smStore
{
	std::unordered_map<uint32_t, TcpPacket> tcpSmStore[MAX_TCP_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool tcpSmBusy[MAX_TCP_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t tcpSmCnt[MAX_TCP_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, UdpPacket> udpSmStore[MAX_UDP_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool udpSmBusy[MAX_UDP_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t udpSmCnt[MAX_UDP_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, DnsPacket> dnsSmStore[MAX_DNS_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool dnsSmBusy[MAX_DNS_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t dnsSmCnt[MAX_DNS_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, AAAPacket> aaaSmStore[MAX_AAA_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool aaaSmBusy[MAX_AAA_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t aaaSmCnt[MAX_AAA_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, TcpPacket> unTcpSmStore[MAX_UNM_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool unTcpSmBusy[MAX_UNM_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t unTcpSmCnt[MAX_UNM_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];

	std::unordered_map<uint32_t, UdpPacket> unUdpSmStore[MAX_UNM_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	bool unUdpSmBusy[MAX_UNM_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
	uint32_t unUdpSmCnt[MAX_UNM_SM_SUPPORT][MAX_INTERFACE_SUPPORT][MAX_ROUTER_PER_INTERFACE][10];
}

namespace FlushRepo
{
	std::unordered_map<uint32_t, tcpSession> tcpFlStore[MAX_FLUSHER_SUPPORT][MAX_TCP_SM_SUPPORT][10];
	uint32_t tcpFlCnt[MAX_FLUSHER_SUPPORT][MAX_TCP_SM_SUPPORT][10] = {0};

	std::unordered_map<uint32_t, udpSession> udpFlStore[MAX_FLUSHER_SUPPORT][MAX_UDP_SM_SUPPORT][10];
	uint32_t udpFlCnt[MAX_FLUSHER_SUPPORT][MAX_UDP_SM_SUPPORT][10] = {0};

	std::unordered_map<uint32_t, dnsSession> dnsFlStore[MAX_FLUSHER_SUPPORT][MAX_UDP_SM_SUPPORT][10];
	uint32_t dnsFlCnt[MAX_FLUSHER_SUPPORT][MAX_UDP_SM_SUPPORT][10] = {0};

	std::unordered_map<uint32_t, aaaSession> aaaFlStore[MAX_FLUSHER_SUPPORT][MAX_AAA_SM_SUPPORT][10];
	uint32_t aaaFlCnt[MAX_FLUSHER_SUPPORT][MAX_AAA_SM_SUPPORT][10] = {0};

}

namespace UnFlushRepo
{
	std::unordered_map<uint32_t, tcpSession> uTcpFlStore[MAX_UNM_SM_SUPPORT][10];
	uint32_t uTcpFlCnt[MAX_UNM_SM_SUPPORT][10] = {0};

	std::unordered_map<uint32_t, udpSession> uUdpFlStore[MAX_UNM_SM_SUPPORT][10];
	uint32_t uUdpFlCnt[MAX_UDP_SM_SUPPORT][10] = {0};

	std::unordered_map<uint32_t, dnsSession> uDnsFlStore[MAX_UNM_SM_SUPPORT][10];
	uint32_t uDnsFlCnt[MAX_UDP_SM_SUPPORT][10] = {0};
}

